Update packaging

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,74 +1,129 @@
 #!/usr/bin/make -f
+# -*- makefile -*-
 
-# Uncomment this to turn on verbose mode.
-# export DH_VERBOSE = 1
+DPKG_EXPORT_BUILDFLAGS = 1
+include /usr/share/dpkg/buildflags.mk
+
+export BUILD_TLS = yes
+export CFLAGS CPPFLAGS LDFLAGS
+export DEB_BUILD_MAINT_OPTIONS = hardening=+all optimize=+lto
+export DEB_CFLAGS_MAINT_APPEND = -I/usr/include/liblzf
+export DEB_LDFLAGS_MAINT_APPEND = -Wl,-no-as-needed -ldl -latomic -llzf
+
+VALKEY_DOC_VERSION = 9.0.0
+
+# Build jemalloc in parallel
+ifneq (,$(filter parallel=%,$(DEB_BUILD_OPTIONS)))
+	NUMJOBS = $(patsubst parallel=%,%,$(filter parallel=%,$(DEB_BUILD_OPTIONS)))
+	MAKEFLAGS += -j$(NUMJOBS)
+	export MAKEFLAGS
+endif
 
 %:
 	dh $@
 
+override_dh_auto_clean:
+	dh_auto_clean
+	rm -f src/release.h debian/*.service
+	rm -rf valkey-doc-$(VALKEY_DOC_VERSION) valkey-doc-$(VALKEY_DOC_VERSION).tar.gz
+
 override_dh_auto_build:
-	dh_auto_build -- PREFIX=../debian/valkey/usr
-	# Add custom build commands here if needed
+	dh_auto_build -- V=1 USE_SYSTEM_JEMALLOC=yes USE_SYSTEMD=yes USE_JEMALLOC=yes
 
-override_dh_auto_install:
-	dh_auto_install -- PREFIX=../debian/valkey/usr
-
-	# Main package installation steps
-	# Cleaning up not needed directories as per RPM spec
-	rm -rf debian/valkey/usr/share/valkey
-
-	# Installing configuration and support files
-	install -D -m 0644 debian/valkey.sysusers debian/valkey/etc/sysusers.d/valkey.conf
-	install -D -m 0644 debian/valkey.logrotate debian/valkey/etc/logrotate.d/valkey
-	install -D -m 0644 debian/valkey-limit-systemd debian/valkey/lib/systemd/system/valkey.service.d/limit.conf
-	install -D -m 0644 debian/valkey-limit-systemd debian/valkey/lib/systemd/system/valkey-sentinel.service.d/limit.conf
-
-	# Creating necessary directories
-	install -d debian/valkey/var/lib/valkey
-	install -d debian/valkey/var/log/valkey
-	install -d debian/valkey/var/run/valkey
-	install -d debian/valkey/etc/valkey
-	install -d debian/valkey/usr/lib/valkey/modules
-
-	install -D -m 0644 debian/../src/modules/*  debian/valkey/usr/lib/valkey/modules/
-	install -D -m 0644 debian/../valkey.conf debian/valkey/etc/valkey/valkey.conf
-	install -D -m 0644 debian/../sentinel.conf debian/valkey/etc/valkey/sentinel.conf
-	# Service configuration
-	install -D -m 0644 debian/valkey-sentinel.service debian/valkey/lib/systemd/system/valkey-sentinel.service
-
-	# Permissions for executables
-	chmod 755 debian/valkey/usr/bin/valkey-*
-
-	# RPM macro configuration equivalent
-	install -D -m 0644 debian/macros.valkey debian/valkey/etc/default/valkey
-
-	# Sysconfig files
-	install -D -m 644 debian/valkey.sysconfig debian/valkey/etc/sysconfig/valkey
-	install -D -m 644 debian/valkey-sentinel.sysconfig debian/valkey/etc/sysconfig/valkey-sentinel
-
-	# Script files for compat package
-	install -D -m 755 debian/conf_update.sh debian/valkey-compat/usr/libexec/conf_update.sh
-
-	# Devel package files
-	install -D -m 0644 src/valkeymodule.h debian/valkey-devel/usr/include/valkeymodule.h
-
-	mkdir -p debian/valkey/usr/share/doc/valkey/
-	cp deps/lua/COPYRIGHT debian/valkey/usr/share/doc/valkey/COPYRIGHT-lua
-	cp deps/jemalloc/COPYING debian/valkey/usr/share/doc/valkey/COPYING-jemalloc
-	cp deps/hiredis/COPYING debian/valkey/usr/share/doc/valkey/COPYING-hiredis-BSD-3-Clause
-	cp deps/hdr_histogram/LICENSE.txt debian/valkey/usr/share/doc/valkey/LICENSE-hdrhistogram
-	cp deps/hdr_histogram/COPYING.txt debian/valkey/usr/share/doc/valkey/COPYING-hdrhistogram
-	cp deps/fpconv/LICENSE.txt debian/valkey/usr/share/doc/valkey/LICENSE-fpconv
-
-override_dh_install:
-	# Additional installation steps if required
-
-override_dh_clean:
-	dh_clean
-	# Clean up steps if required
-
-override_dh_builddeb:
-	dh_builddeb -- -Zgzip
+# Build documentation if not nodoc profile
+ifeq (,$(filter nodoc,$(DEB_BUILD_PROFILES)))
+	# Download and build valkey-doc if not present
+	if [ ! -d valkey-doc-$(VALKEY_DOC_VERSION) ]; then \
+		if [ ! -f valkey-doc-$(VALKEY_DOC_VERSION).tar.gz ]; then \
+			wget -q https://github.com/valkey-io/valkey-doc/archive/$(VALKEY_DOC_VERSION)/valkey-doc-$(VALKEY_DOC_VERSION).tar.gz; \
+		fi; \
+		tar xzf valkey-doc-$(VALKEY_DOC_VERSION).tar.gz; \
+	fi
+	if [ -d valkey-doc-$(VALKEY_DOC_VERSION) ]; then \
+		$(MAKE) -C valkey-doc-$(VALKEY_DOC_VERSION) VALKEY_ROOT=$(CURDIR) || true; \
+		$(MAKE) -C valkey-doc-$(VALKEY_DOC_VERSION) html VALKEY_ROOT=$(CURDIR) || true; \
+	fi
+endif
 
 override_dh_auto_test:
+ifeq (,$(filter nocheck,$(DEB_BUILD_OPTIONS)))
+	# Generate a root CA and server certificate for testing
+	./utils/gen-test-certs.sh
+	# Avoid race conditions in upstream testsuite
+	./runtest --clients 1 --verbose --dump-logs --tls || true
+	timeout 30m ./runtest-cluster --tls || true
+	./runtest-sentinel || true
+	# Clean up after gen-test-certs.sh
+	rm -rf tests/tls || true
+	# Other cleanup
+	find tests/tmp ! -name .gitignore -type f -exec rm -rfv {} +
+endif
 
+override_dh_auto_install:
+	# Install binaries
+	install -D -m 0755 src/valkey-server debian/tmp/usr/bin/valkey-server
+	install -D -m 0755 src/valkey-cli debian/tmp/usr/bin/valkey-cli
+	install -D -m 0755 src/valkey-benchmark debian/tmp/usr/bin/valkey-benchmark
+	# valkey-check-aof and valkey-check-rdb are the same binary as valkey-server
+	# (hardlinks in the source tree). Install as symlinks to avoid duplicate
+	# .build-id debug files that cause dbgsym package conflicts.
+	ln -sf valkey-server debian/tmp/usr/bin/valkey-check-aof
+	ln -sf valkey-server debian/tmp/usr/bin/valkey-check-rdb
+	
+	# Sentinel is a symlink
+	ln -sf valkey-server debian/tmp/usr/bin/valkey-sentinel
+	
+	# Install configuration files
+	install -D -m 0640 valkey.conf debian/tmp/etc/valkey/valkey.conf
+	install -D -m 0640 sentinel.conf debian/tmp/etc/valkey/sentinel.conf
+	
+	# Install development headers
+	install -D -m 0644 src/valkeymodule.h debian/tmp/usr/include/valkeymodule.h
+	install -D -m 0644 src/redismodule.h debian/tmp/usr/include/redismodule.h
+	
+	# Create Redis compatibility symlinks
+	for bin in valkey-server valkey-cli valkey-benchmark valkey-check-aof valkey-check-rdb valkey-sentinel; do \
+		redisbin=$$(echo $$bin | sed 's/valkey/redis/'); \
+		ln -sf $$bin debian/tmp/usr/bin/$$redisbin; \
+	done
+	
+	# Install documentation if built
+ifeq (,$(filter nodoc,$(DEB_BUILD_PROFILES)))
+	if [ -d valkey-doc-$(VALKEY_DOC_VERSION)/_build/html ]; then \
+		install -d debian/tmp/usr/share/doc/valkey-doc; \
+		cp -r valkey-doc-$(VALKEY_DOC_VERSION)/_build/html/* debian/tmp/usr/share/doc/valkey-doc/; \
+	fi
+	if [ -d valkey-doc-$(VALKEY_DOC_VERSION)/_build/man ]; then \
+		install -d debian/tmp/usr/share/man; \
+		cp -r valkey-doc-$(VALKEY_DOC_VERSION)/_build/man/* debian/tmp/usr/share/man/; \
+	fi
+endif
+	
+	# Generate systemd service files
+	debian/bin/generate-systemd-service-files
+
+override_dh_fixperms:
+	dh_fixperms
+	# Configuration files should be readable by valkey group only
+	chmod 0640 debian/percona-valkey-server/etc/valkey/valkey.conf || true
+	chmod 0640 debian/percona-valkey-sentinel/etc/valkey/sentinel.conf || true
+
+override_dh_compress:
+	dh_compress -Xredis-trib.rb
+
+override_dh_installchangelogs:
+	dh_installchangelogs --keep 00-RELEASENOTES
+
+override_dh_installinit:
+	dh_installinit -ppercona-valkey-server --name=valkey-server
+	dh_installinit -ppercona-valkey-sentinel --name=valkey-sentinel
+
+override_dh_installsystemd:
+	dh_installsystemd -ppercona-valkey-server --name=valkey-server
+	dh_installsystemd -ppercona-valkey-server --name=valkey-server@
+	dh_installsystemd -ppercona-valkey-sentinel --name=valkey-sentinel
+	dh_installsystemd -ppercona-valkey-sentinel --name=valkey-sentinel@
+
+.PHONY: override_dh_auto_build override_dh_auto_install override_dh_auto_test \
+        override_dh_fixperms override_dh_compress override_dh_installchangelogs \
+        override_dh_installinit override_dh_installsystemd
